import re

from code_mirror import mirror_code


def clean_partition_text(text):
    return (
        str(text)
        .replace("|", " ")
        .replace("[", " ")
        .replace("]", " ")
        .replace("\n", " ")
        .replace("\r", " ")
        .strip()
    )


def parse_single_nli_code(code):
    if code is None:
        return None

    code = str(code).strip()

    if not (code.startswith("[") and code.endswith("]")):
        return None

    parts = code[1:-1].split("|", 5)

    if len(parts) != 6:
        return None

    parts = [part.strip() for part in parts]

    return {
        "code_type": parts[0],
        "module_id": parts[1],
        "command": parts[2],
        "emotion": parts[3],
        "user_text": parts[4],
        "narration": parts[5],
        "raw": code,
    }



def make_core_chat_code(user_text, user_emotion="neutral"):
    """Creates an NLI input that can deliver normal conversation to the LLM even without module status."""
    user_text = clean_partition_text(user_text)
    user_emotion = clean_partition_text(user_emotion) or "neutral"

    if not user_text:
        raise ValueError("User utterance is empty")

    return f"[R|none|none|{user_emotion}|{user_text}|]"

def extract_nli_blocks(response_text):
    if response_text is None:
        return []

    text = str(response_text).strip()
    text = text.replace("```text", "")
    text = text.replace("```json", "")
    text = text.replace("```", "")

    blocks = re.findall(r"\[[^\[\]\r\n]*\]", text)
    results = []

    for block in blocks:
        parsed = parse_single_nli_code(block)
        if parsed is not None:
            # Display valid codes generated by HF, including O/none, regardless of whether they are actually sent to a module
            mirror_code(block)
            results.append(parsed)

    return results


def make_voice_report_code(original_report_code, user_text, user_emotion):
    """Creates an NLI R code from voice input.

    If a recent R code exists, combine the voice with that module status,
    and if no recent R code exists, create a module-free normal-conversation R code.
    """
    if original_report_code is None:
        return make_core_chat_code(
            user_text=user_text,
            user_emotion=user_emotion,
        )

    parsed = parse_single_nli_code(original_report_code)

    if parsed is None:
        raise ValueError("Stored R code format is invalid")

    if parsed["code_type"].upper().strip() != "R":
        raise ValueError("Stored code is not R type")

    return (
        f"[R|"
        f"{clean_partition_text(parsed['module_id'])}|"
        f"{clean_partition_text(parsed['command'])}|"
        f"{clean_partition_text(user_emotion)}|"
        f"{clean_partition_text(user_text)}|"
        f"]"
    )


def print_parsed_result(parsed, index):
    print()
    print(f"========== NLI PARSED {index} ==========")
    print("① CODE TYPE :", parsed["code_type"])
    print("② MODULE ID :", parsed["module_id"])
    print("③ COMMAND   :", parsed["command"])
    print("④ EMOTION   :", parsed["emotion"])
    print("⑤ USER TEXT :", parsed["user_text"])
    print("⑥ NARRATION :", parsed["narration"])
    print("RAW          :", parsed["raw"])
    print("========================================")
